apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: inpost
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: springboot-api-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: dev-global-cluster-0
        env: dev
        replicaCount: "3"
        url: https://dev-global-cluster-0
        host: dev-global-cluster-0
      - cluster: prd-global-cluster-5
        env: prd
        replicaCount: "5"
        url: https://prd-global-cluster-5
        host: prd-global-cluster-5
  template:
    metadata:
      name: springboot-api-{{ .env }}-{{ .cluster }} # Application name: springboot-api-dev, springboot-api-prd.  Include cluster name.
      namespace: springboot-api
      finalizers:
      - resources.argocd.argoproj.io/foreground
    spec:
      project: inpost
      source:
        repoURL: 'https://github.com/lukasz-biernat/springboot-api.git'
        targetRevision: HEAD
        helm:
#          chart: springboot-api # Name of the helm chart in the repository
          parameters:
          - name: replicaCount
            value: '{{ .replicaCount }}'
          - name: env
            value: '{{ .env }}'
          - name: ingress.host
            value: '{{ .host }}'
      destination:
        server: 'https://{{ .cluster }}'
        namespace: springboot-api
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
