apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-api-configmap
data:
  config.json: |
    {
      "appName": "SpringBootAPI",
      "version": "1.0.0",
      "environment": "{{ .Values.env }}" # dev or prd
    }
