apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-api
spec:
  replicas: {{ .Values.replicaCount | int }} # 3 for dev, 5 for prd
  selector:
    matchLabels:
      app: springboot-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: springboot-api
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: springboot-api
        image: ghcr.io/lukasz-biernat/busybox:stable
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: logs
        - containerPort: 8082
          name: soap
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP # Pod IP
        - name: SECRET_KEY_1
          valueFrom:
            secretKeyRef:
              name: springboot-api-secret
              key: secret-key-1
        - name: SECRET_KEY_2
          valueFrom:
            secretKeyRef:
              name: springboot-api-secret
              key: secret-key-2
        args:
        - "--spring.profiles.active={{ .Values.env }}" # dev or prd
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.json
          subPath: config.json
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "wget http://localhost:8080/service/shutdown"]
      volumes:
      - name: config-volume
        configMap:
          name: springboot-api-configmap
