apiVersion: v1
kind: Service
metadata:
  name: springboot-api-service
spec:
  type: ClusterIP
  selector:
    app: springboot-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: logs
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: soap
    port: 8082
    targetPort: 8082
    protocol: TCP
